# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
weather_df = pd.read_csv("../output_files/cities.csv")
weather_df

,Unnamed: 0,Country,City,Date,Max Temp,Cloudiness,Humidity,Lat,Lng,Wind Speed
0,0,ZA,Port Elizabeth,1651623820,65.32,0,93,-33.9180,25.5701,10.36
1,1,UZ,Yangi Marg`ilon,1651623847,68.72,100,60,40.4272,71.7189,4.61
2,2,RU,Tiksi,1651623790,15.66,52,87,71.6872,128.8694,3.74
3,3,AO,Cabinda,1651623847,78.19,84,91,-5.5500,12.2000,5.35
4,4,MU,Quatre Cocos,1651623848,75.31,39,81,-20.2078,57.7625,10.29
...,...,...,...,...,...,...,...,...,...,...
595,595,SO,Hobyo,1651624160,81.37,82,68,5.3505,48.5268,10.76
596,596,TJ,Obigarm,1651624161,56.03,100,91,38.7173,69.7088,6.20
597,597,CN,Baoning,1651624161,60.66,0,88,25.3378,110.0260,0.00
598,598,VN,Tam Ky,1651624162,71.98,100,85,15.5667,108.4833,5.95
599,599,PT,Camacha,1651624163,58.42,75,77,33.0833,-16.3333,11.50

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure